#!/usr/bin/env python3

"""
Build a static JSON representation of the database schema for CodeMirror hints.

The script reads the generated SQLite schema database (see make_db.py) and
emits `schema=<json>;` to stdout so the caller can redirect it into
`src/static/js/bundle/schema.js`.
"""

import argparse
import json
import os
import sqlite3
from typing import Dict, List

DEFAULT_VIEWS = [
    "adoption",
    "animal",
    "animalcontrol",
    "animalfound",
    "animallost",
    "animalmedicalcombined",
    "animalmedicaltreatment",
    "animaltest",
    "animalvaccination",
    "animalwaitinglist",
    "owner",
    "ownercitation",
    "ownerdonation",
    "ownerlicence",
    "ownertraploan",
    "ownervoucher",
]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export ASM3 schema metadata as JSON")
    parser.add_argument(
        "--db",
        default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "schema.db"),
        help="Path to the SQLite schema database generated by make_db.py",
    )
    parser.add_argument(
        "--views",
        nargs="*",
        default=DEFAULT_VIEWS,
        help="Additional v_* views to include (defaults match ASM3)",
    )
    return parser.parse_args()


def _read_table_columns(
    cursor: sqlite3.Cursor, table: str, is_view: bool = False
) -> List[str]:
    pragma_target = f"v_{table}" if is_view else table
    cursor.execute(f"pragma table_info({pragma_target})")
    return [row[1] for row in cursor.fetchall()]


def build_schema(db_path: str, views: List[str]) -> Dict[str, List[str]]:
    conn = sqlite3.connect(db_path)
    try:
        cursor = conn.cursor()
        schema: Dict[str, List[str]] = {}

        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        for (table_name,) in cursor.fetchall():
            schema[table_name] = _read_table_columns(cursor, table_name)

        for view in views:
            schema[f"v_{view}"] = _read_table_columns(cursor, view, is_view=True)

        return schema
    finally:
        conn.close()


def main() -> None:
    args = _parse_args()
    schema = build_schema(os.path.abspath(args.db), args.views)
    print(f"schema={json.dumps(schema)};")


if __name__ == "__main__":
    main()
